### ISSUE TITLE
[BUG] 在没有相机瞄准的第三人称，用鼠标拖拽视角时，玩家模型的头部会随之转动而不是静止

### ISSUE THREAD

**Issue by MoYuEnder** [Leawind/Third-Person#106]
## Describe the bug
版本 1.20.1
Forge 47.2.16
MOD版本 2.0.8 b5

如标题，未开启瞄准状态时，拖拽鼠标并任意方向旋转都会让玩家模型的头部按那个方向转动，幅度够大的话甚至会转动身体，理应来说不该有这种情况。

## Reproduce

打开第三人称视角，关闭瞄准状态，用鼠标挪动并观察玩家模型注视方向的变化。

## Expected behavior

希望除非鼠标点击或方向键挪动，否则玩家模型的头部不会有“修正”，这样方便摆拍。

## Additional context
附视频
https://github.com/Leawind/Third-Person/assets/120367297/a6a8690d-221b-461e-b1aa-2e752c22e529

**Comment by Leawind** [comment]
可是视频里没发现哪不对劲耶
