### ISSUE TITLE
spyglass shifting to a partcular point in first person

### ISSUE THREAD

**Issue by PokeTlc** [Leawind/Third-Person#107]
## Describe the bug

basically when spyglass is used in first persion, it fixates on one point instead of focusing at the point clicked, even if the one point is in another direction

## Reproduce

use spyglass i first person, it zooms in on one point

## Expected behavior

spyglass working as minecraft intended

**Comment by Leawind** [comment]
Could provide the game log

**Comment by Leawind** [comment]
fixed in 7703fb0292e3c427a904773b60d6b4b0f94b272b

**Comment by Leawind** [comment]
duplicated with #78
