### ISSUE TITLE
添加关闭身体转向的配置选项以兼容史诗战斗。Make an config option to disable body rotation when player moves.

### ISSUE THREAD

**Issue by XM666-Dev** [Leawind/Third-Person#11]
![2023-11-09_09 48 31](https://github.com/LEAWIND/Third-Person-Perspective/assets/99076011/330ff783-ed19-4bf8-bb95-cf93cee3ff2b)
将该模组与史诗战斗一起使用，第三人称时按移动键的身体转向会导致很难击中怪物，比如要躲避攻击按s键后退两步，直接就会让玩家回头打不中怪，并且配置文件里也关不掉这个功能。

**Comment by XM666-Dev** [comment]
这个问题的影响很大，导致史诗战斗基本没法玩了，因为身体会乱转，攻击会一直打不中敌人。
设置里虽然有瞄准键位，但是反复切换太麻烦了，是否可以完全关闭此功能？

**Comment by XM666-Dev** [comment]
并且这个模组会让史诗战斗模组在使用弓和弩时第三人称视角发生异常，卡顿、抖动等。

**Comment by Leawind** [comment]
重构以后会想办法修复的哈
