### ISSUE TITLE
Spyglass snaps to the north upon use

### ISSUE THREAD

**Issue by macaconheiro** [Leawind/Third-Person#118]
Bug Description:
1.20.1 - v2.0.8-beta.5 glitch found: Spyglass changes player orientation to the north upon being used, no matter where the player is looking prior to use.

Steps to reproduce the behaviour:
1. Equip a spyglass;
2. Look somewhere that isn't straight north;
3. Use the spyglass;
4. Spyglass snaps to the north unexpectedly.

Expected behaviour:
The player should maintain the original orientation regardless of spyglass usage.

Additional context:
No mod conflicts. Glitch is still found when tested in isolation.

**Comment by Leawind** [comment]
Duplicate with #78
