### ISSUE TITLE
窄道，抬头低头视角优化，透明度系数优化建议

### ISSUE THREAD

**Issue by sinterde** [Leawind/Third-Person#119]
非常棒的模组，玩了好久了，发现三点体验上可以优化的地方：
（这些细节均来自“越肩视角”）（如果觉得表达不清，请请提醒我，我可以去拍录个视频）

**1，窄道镜头居中：**
* 窄道镜头居中——在一格宽的矿道里视角与角色挨的很近，准星没和角色重叠的时候不会有半透明效果，加上摄像机离的远的话就导致前方的路被人物挡住，推荐视角向中心收窄的的时候也同时进行拉近，窄到一定程度时直接居中，这样在半透明更灵活的同时挖矿也更方便

**2，类门框场景的镜头问题：**
* 人物进门（洞）场景优化——建议摄像机的收窄以人物所在位置的宽度为主要考量，目前进入狭窄空间时（进门，一格矿道），人物走进去一段距离后，摄像机进入矿道时准星才会向中心靠拢，在这之前准星都会在入口处的方块上，想挖正前方方块得把镜头斜过去
屏幕中心最好能在各种情况下瞄在人物前方，而不是落在墙上，不然的话在瞄准的时候人物会频繁的看向墙面

**3，透明度改进：**
 * 半透明程度可调——半透明的的系数可以再高一点，目前视角拉近透明力度不够大，需要费力去看，要是透明度系数也能做一个配置选项就好了
 * 半透明距离限制——有时左右横移或移动跳跃时总是会触发半透明（准星人物重叠），希望能够加入一定距离内半透明才生效的配置选项

**Comment by Leawind** [comment]
1. 我试试加大相机的碰撞体积，应该也能解决。

2. 这个确实可以，最早的版本就有类似的功能，当两边都有方块时自动切换到居中。后来重构的时候感觉这个功能有点多余就去掉了。

要让准星始终保持在人物正前方的话，建议长按capslock居中。

3. 这两个功能都可以加。
