### ISSUE TITLE
forge 1.19.2 port

### ISSUE THREAD

**Issue by Trickster-4** [Leawind/Third-Person#12]
please port it for 1.19.2!!! your mod is AWESOME! exactly what a lot of people need for their RPG action modpacks.
unfortunately most of them are only avaliable in 1.19.2, including mine.
hope to see it very soon!

**Comment by Leawind** [comment]
I plan to backport it to 1.19.2 in two months. I've been quite busy lately, so development might be delayed.

**Comment by CFog1** [comment]
I might also  backport it too and see if it works

**Comment by Trickster-4** [comment]
> I might also backport it too and see if it works

nice! please do! I'm very excited to see it ^^

**Comment by CFog1** [comment]
sadly the latest version had some gradle problems so I couldn't backport it

**Comment by Trickster-4** [comment]
> sadly the latest version had some gradle problems so I couldn't backport it

yeah i saw.
couldn't you build it then?

**Comment by bubin7766** [comment]
> sadly the latest version had some gradle problems so I couldn't backport it

With the latest stable release out now do you think you could try it again?

**Comment by Trickster-4** [comment]
> I plan to backport it to 1.19.2 in two months. I've been quite busy lately, so development might be delayed.

hey i saw you recently doing a backport! thanks!
however, it is avaliable in 1.19.4 only. do you have plans of making it be compatible in more versions or make a separate 1.19.2 version of the mod? I wanna test it so badly 😭

**Comment by CFog1** [comment]
> [bubin7766](/bubin7766)

sorry if it took me long to reply and yes I think I could possibly do it

**Comment by bubin7766** [comment]
> > [bubin7766](/bubin7766)
> 
> sorry if it took me long to reply and yes I think I could possibly do it

That’s great to hear! although from the looks of it the mod author continues to make pretty great updates day after day, so I’m not sure how feasible that port would be in the end

**Comment by CFog1** [comment]
they might just do it before me

**Comment by Leawind** [comment]
> > I plan to backport it to 1.19.2 in two months. I've been quite busy lately, so development might be delayed.
> 
> hey i saw you recently doing a backport! thanks! however, it is avaliable in 1.19.4 only. do you have plans of making it be compatible in more versions or make a separate 1.19.2 version of the mod? I wanna test it so badly 😭

I'm trying to port it to 1.19.2 now

**Comment by Leawind** [comment]
> [CFog1](/CFog1)

It seems YACL cannot be used in version 1.19.2 and earlier. So I'm gonna use Cloth Config API to build the configuration screen.

**Comment by CFog1** [comment]
that exactly what happened to me

**Comment by CFog1** [comment]
also can you add a option to the config to disable the custom head movement the mod adds? Since one of the mods I use bug out.

**Comment by Leawind** [comment]
> also can you add a option to the config to disable the custom head movement the mod adds? Since one of the mods I use bug out.

Maybe disable these options can solve?
* `player_rotate_with_camera_when_not_aiming`
* `rotate_to_moving_direction`
* `auto_rotate_interacting`

**Comment by CFog1** [comment]
I think so, where can I find this options?

**Comment by Leawind** [comment]
> I think so, where can I find this options?

In tab `Common`:
Group *Player Rotation*:
* Force player to Rotate with Camera when Not Aiming
* Automatically Rotate Player to Moving Direction\

And in tab `Miscellaneous`:
Group *Player Rotation during interaction*:
* Auto-Rotate During Interaction

**Comment by CFog1** [comment]
Is this in the root folders or in the mod's config?

**Comment by bubin7766** [comment]
This is in the config screen

**Comment by CFog1** [comment]
ok

**Comment by CFog1** [comment]
the 1.20.1 branch needs to update their config as it doesn't have all the options

**Comment by bubin7766** [comment]
> the 1.20.1 branch needs to update their config as it doesn't have all the options

It doesn't have all the config options because Leawind is still working on perfecting the mod before porting it to other versions
Ironing out all the bugs and adding in more features is a priority vs having to do the same work multiple times for different versions of the game

**Comment by CFog1** [comment]
ok

**Comment by bubin7766** [comment]
> > [LEAWIND](/LEAWIND)
> 
> It seems YACL cannot be used in version 1.19.2 and earlier. So I'm gonna use Cloth Config API to build the configuration screen.

I know you're working with Cloth Config atm but if possible I closely follow another mod author who has made their own config system called Carbon Config. I really believe they have a good system working across Forge and Fabric even spanning 1.7.10 till 1.20.4

When I asked him how it could be used they said

> There are 3 ways you can use carbon config GUIs:
> 
> - Use carbon configs config system. (Auto detected and build), (Forge/Fabric)
> - Use forge config system (Auto detected and build) (Forge)
> - Implement the required Interfaces and manually create the GUI interface. But that is a lot less than the entire GUI. It's just accessors. (Manually) (Forge/Fabric)

He also linked me to [this example](https://github.com/Carbon-Config-Project/CarbonConfigLib/blob/ef3b44e233501214ac98d7d535ce0aab8202b8e0/EXAMPLES.md)
But here is the [mod page](https://www.curseforge.com/minecraft/mc-mods/carbon-config) and [feature list](https://github.com/Carbon-Config-Project/CarbonConfig/blob/1.19.2/README.md) for more info

I once again want to thank you for all your hard work into creating such an amazing mod, it always amazes me watching the community create amazing mods and even more so when small mod authors work together to build each other up

**Comment by Leawind** [comment]
> [bubin7766](/bubin7766)

Thanks for your suggestion. Carbon Config is awesome, I gave it a star. But it seems that Carbon Config does not support fabrics below 1.18.

**Comment by Speiger** [comment]
> > [bubin7766](/bubin7766)
> 
> Thanks for your suggestion. Carbon Config is awesome, I gave it a star. But it seems that Carbon Config does not support fabrics below 1.18.


o/ carbon config dev here.
What mc version do you specifically request?

I'll have to look into it if we can port there since we are new to fabric (we are mainly forge devs)

**Comment by Leawind** [comment]
> o/ carbon config dev here. What mc version do you specifically request?
> 
> I'll have to look into it if we can port there since we are new to fabric (we are mainly forge devs)

It mostly depends on what mc versions players want my mod to be ported to.
What I know so far are 1.16.5, 1.12.2, 1.8.9

**Comment by Speiger** [comment]
@LEAWIND I wasn't aware that fabric existed before 1.14.4 (besides a few manual ports from buddies)

And i am not sure how easily we can support before 1.16.5 for fabric because before 1.16.5 we are using forge mappings.
Anything after that should be easily supportable because we are using Mojang mappings which means the difference is:
- Delete forge specific code
- Make fabric specific changes (get accessors/install modcompat)

And Mod menu, which you kinda rely on in fabric doesn't even go before 1.14.4.
So 1.16.5 wouldn't be an issue, anything before that will be difficult.
Though we would accept pull requests with ports, and we would maintain it too.
(Maintain would be bugfixes, and rarely feature updates in this case)

**Comment by Leawind** [comment]
@Speiger I didn't notice that (＃°Д°) That means I only need to port to 1.16.5. Thank you for your awesome work!

**Comment by Trickster-4** [comment]
hey there!
I tried compiling it and test it on my modpack, however i'm having this error right here that makes it impossible to load the mod:

net.minecraftforge.fml.ModLoadingException: Mod File leawind_third_person-v2.0.1-mc1.19.2-forge.jar needs language provider javafml:45 or above to load
§7We have found 43

what should I do?

**Comment by Trickster-4** [comment]
aay thanks!!! your recent update allowed me to test it in 1.19.2.
lemme say it is amazing!!!! thank you so much for this port.

is there an option to set how much the player will offset when moving?
when going to high speeds the player goes away too much.
![image](https://github.com/LEAWIND/Third-Person/assets/90531548/ebea2c40-84bb-4b8c-9b6c-290da9e4a0f2)

**Comment by Speiger** [comment]
@LEAWIND small update on my side.
Carbon Config now has a 1.16.5 fabric port.

So we now support:
- Forge: 1.7.10->1.20.4
- Fabric: 1.16.5 -> 1.20.4
- Neoforge: 1.20.2-> 1.20.4
