### ISSUE TITLE
左中右镜头切换问题

### ISSUE THREAD

**Issue by sinterde** [Leawind/Third-Person#120]
如镜头在右边，长按按键切换到中间后，再次切换会越肩，镜头会先返回右边，然后突然切换到左边。
建议居中切换为越肩后，能保持先前的方向

**Comment by Leawind** [comment]
终于有人提出来了😂
我以为没有人会发现这个问题，所以一直懒得改🦥

**Comment by sinterde** [comment]
哈，你的模组非常棒，已经是我玩mc的必选项了，自定义程度比越肩高，可以自己手动适配很多模组🥰

**Comment by Leawind** [comment]
感谢支持！可以告诉我你手动适配了哪些模组吗?
