### ISSUE TITLE
Incorrect block placement with Valkyrien Skies installed

### ISSUE THREAD

**Issue by AzrannAVANA** [Leawind/Third-Person#124]
## Describe the bug

Hello. I've found a rather strange bug that boils down to this:
When entering third person, the game doesn't register any new faces the player may face. As such, all blocks will be placed at the last block the player faced before switching to third person.

https://github.com/user-attachments/assets/2d81222c-8ac2-461f-b189-0a81087e539b

## Reproduce

1. Face a block in first person
1. Enter third person, then face another
1. Upon trying to place a block, it will be placed on the first position before switching to third person.

## Expected behavior

The block should be placed where the player crosshair or where the player looks at any time.

## Additional context

I have a rather extensive modlist, which I'll link here: [Modlist.txt](https://github.com/user-attachments/files/16313373/Modlist.txt)
For testing, there is also my modpack itself hosted on Modrinth: https://modrinth.com/modpack/vortex-foundations

Thank you, and have a very nice day.

**Comment by Leawind** [comment]
When there's no other mod installed, it works fine.
It looks like conflict with another mod.

**Comment by ContagiousStorm** [comment]
From my testing the issue is caused by Valkyrien Skies, which is a real bummer

**Comment by AzrannAVANA** [comment]
Ah yea it must be.. VS breaks a LOT of mods sadly.

**Comment by Leawind** [comment]
Duplicate of #79

**Comment by AzrannAVANA** [comment]
Well since this is a duplicate, I believe this is redundant...
