### ISSUE TITLE
因在游玩过程中开启第三人称后强制关机从而造成游戏无法使用第三人称Mod，一旦启用Mod游戏就会崩溃

### ISSUE THREAD

**Issue by LikeNkil** [Leawind/Third-Person#128]
这个是HMCL导出的崩溃日志
[minecraft-exported-crash-info-2024-07-23T19-38-19.zip](https://github.com/user-attachments/files/16356315/minecraft-exported-crash-info-2024-07-23T19-38-19.zip)

**Comment by Leawind** [comment]
疑似强制关机导致模组配置文件没有正确保存，所以配置文件损坏。
删除游戏运行目录下config目录里本模组的配置文件就可以正常启动了。

这是一个bug，当配置文件损坏时，游戏不应该崩溃，而应该载入默认配置。

**Comment by Leawind** [comment]
另外，应该降低模组配置文件的保存频率。这样可以降低配置文件损坏的几率。
