### ISSUE TITLE
1.20.1最新版本使用后无法启动服务器

### ISSUE THREAD

**Issue by Sakura1Hana** [Leawind/Third-Person#13]
不确定是否为mod冲突
报错记录:https://pastebin.com/j9cR92kM

**Comment by Leawind** [comment]
你似乎在专用服务器上使用了这个mod。
这是一个客户端模组，其中直接访问了一个仅存在于客户端的类 net/minecraft/client/gui/GuiGraphics
所以导致服务器崩溃。

虽然这是一个客户端模组，但当它在服务器端被加载时，我觉得合理的行为应该是不产生任何效果（或仅发出警告），而不是抛出异常导致服务器崩溃。所以我觉得这算是一个bug。

**Comment by Leawind** [comment]
fixed in https://github.com/LEAWIND/Third-Person/commit/c9aa21eccb8dae93087ea0a15281d4b51e2b06c3
