### ISSUE TITLE
与Controllable得兼容性问题

### ISSUE THREAD

**Issue by YeLiShiEr** [Leawind/Third-Person#131]
## Describe the bug

Controllable模组无法控制Leawind's Third Person的视角

## Reproduce

Controllable是一款让手柄能够操作Java我的世界的外设兼容优化模组
Controllable在使用手柄的情况下无法控制视角
Controllable在使用手柄的情况下无法控制人物朝向
Controllable在使用手柄的情况下无法利用按键切换视角，功能例如 F5
其他功能基本正常
游戏版本/1.20.1
mod加载器版本/forge47.2.20
模组版本/Controllable 0.20.3

希望兼容此mod

**Comment by Leawind** [comment]
与 #34 重复
Duplicate with #34
