### ISSUE TITLE
Crash when ...

### ISSUE THREAD

**Issue by AzrannAVANA** [Leawind/Third-Person#134]
## When

Loading world using Embeddium with latest beta

## Crash report

[crash-2024-07-30_12.41.39-client.txt](https://github.com/user-attachments/files/16426505/crash-2024-07-30_12.41.39-client.txt)

**Comment by AzrannAVANA** [comment]
Latest log
[latest.log](https://github.com/user-attachments/files/16426506/latest.log)

**Comment by Leawind** [comment]
Did you try remove leawind's third person and see if it crash?

**Comment by Leawind** [comment]
> ```java
> java.lang.NoSuchMethodError: 'net.minecraft.world.phys.Vec3 net.minecraft.client.Camera.getPosition()'
> 	at net.minecraft.client.renderer.LevelRenderer.handler$fof000$irisflw$renderLayerTail(LevelRenderer.java:3610) ~[client-1.20.1-20230612.114412-srg.jar%23676!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
> ```

It looks like the same problem as https://github.com/leon-o/iris-flw-compat/issues/140

And that guy is not using _Leawind's Third Person_
So I think it's not my bug.
