### ISSUE TITLE
Epic fight. Player head is invisible in 3rd person unless you hold ctrl

### ISSUE THREAD

**Issue by Jetpack-Cat** [Leawind/Third-Person#138]
1.20.1 Forge.

While using epic fight mod, the player head is invisible unless you hold the sprint (ctrl) button. When I hold ctrl to sprint the players head suddenly becomes visible

**Comment by L7GHTBRINGER** [comment]
I have the same Issue but with better combat and animation overhaul

**Comment by ToppyTopology** [comment]
same issue, though for some reason aswell my character wont turn around unless i hold control. The console spams `invalid entity rotation: NaN, discarding`

**Comment by polykatt** [comment]
same issue without epic fight I think its just this mod itself causing the issue

**Comment by Leawind** [comment]
I can't reproduce this.

> same issue, though for some reason aswell my character wont turn around unless i hold control. The console spams `invalid entity rotation: NaN, discarding`

But this is helpful.
Appears to generate NaN when calculating the player's rotation, causing the player's head not to show.

Disable config option _Rotate to interest point_ might solve this

**Comment by Leawind** [comment]
I successfully reproduced this when _Shoulder Surfing_ installed.
