### ISSUE TITLE
有可能移植到fabric吗

### ISSUE THREAD

**Issue by kndxhz** [Leawind/Third-Person#14]
有可能移植到fabric吗，毕竟国内的高版本还是以fabric居多吧，forge兼容性不好

**Comment by Leawind** [comment]
会的，重构版是forge和fabric同步开发

**Comment by Canton1206** [comment]
> 会的，重构版是forge和fabric同步开发

什么时候会出重构版呢？

**Comment by Leawind** [comment]
> > 会的，重构版是forge和fabric同步开发
> 
> 什么时候会出重构版呢？

元旦节前会发布的

**Comment by ImYiFeng** [comment]
> > > 会的，重构版是forge和fabric同步开发
> > 
> > 
> > 什么时候会出重构版呢？
> 
> 元旦节前会发布的
马上元旦了，期待（doge）

**Comment by imyifeng** [comment]
> > > 会的，重构版是forge和fabric同步开发
> > 
> > 
> > 什么时候会出重构版呢？
> 
> 元旦节前会发布的

马上元旦了，期待（doge）
