### ISSUE TITLE
鞘翅飞行时视角被强行拉回

### ISSUE THREAD

**Issue by s-j-y-m** [Leawind/Third-Person#15]
使用鞘翅垂直向上或向下飞行时,视角会被强行快速拉回到近水平方向,
https://cowtransfer.com/s/08a57083eda140
这是触发这个BUG的视频

**Comment by NpTIme** [comment]
这大概不算个bug吧,应该是刻意设计的,希望能加入选项调整

**Comment by s-j-y-m** [comment]
作者在B站回复我了,他说这是刻意设计,但正式版不会有
