### ISSUE TITLE
方块放置异常

### ISSUE THREAD

**Issue by LiYuqin4096** [Leawind/Third-Person#152]
第三人称下放置方块位置异常，具体表现为：第三人称下放置的方块不会放置到准星所指的位置，而是放在切换人称前所指的地方。

https://github.com/user-attachments/assets/7ba81b7a-6f63-4438-957a-0aa424c2ee21

**Comment by LiYuqin4096** [comment]
单独添加时没有这个问题，是模组冲突，但冲突模组未知

**Comment by Hylberra** [comment]
冲突模组疑似为瓦尔基里，会导致放置方块时无论如何瞄准都尝试瞄准从第一人称切换至第三人称之前所对准/交互的最后一个方块的位置
无论创造或生存均存在这一问题

**Comment by LiYuqin4096** [comment]
冲突模组为瓦尔基里附属 clockwork

**Comment by rayhraja** [comment]
i also have this issue, yes i have valkyrien skies. i would be thankful if this could be fixed. thank you

**Comment by Leawind** [comment]
最新版本勉强修复了，你需要在配置中将 _正常旋转模式_ 设置为 _转向相机准星_
The latest version has barely fixed this, you need to set _Normal rotate mode_ in config to _Turn to Camera Crosshair_
