### ISSUE TITLE
Start sprinting randomly

### ISSUE THREAD

**Issue by ghost** [Leawind/Third-Person#159]
## Describe the bug

My character start sprinting when double tapping A or S or D, even when i tap D then S fast, my character start sprinting and this is annoying.

## Reproduce

Go in 3rd person with the mod, go forward then double tap A or S or D and it will start printing.

## Expected behavior

I expect that my character start sprinting only when i double tap W.

## Additional context

No additional context

**Comment by Leawind** [comment]
Duplicate of #155
