### ISSUE TITLE
Crash when going in and out of third person.

### ISSUE THREAD

**Issue by TobiasRunge** [Leawind/Third-Person#168]
## When

Select one:

* launch client
* Join a world
* Enter third person
* Exit third person

## Crash report:  https://mclo.gs/UHG6bup

Please upload the crash report file.

**Comment by Leawind** [comment]
> leawind_third_person: Leawind's Third Person 2.0.8-beta.5

The crash report shows the version you are using is `2.0.8-beta.5`.
This bug looks like has been fixed in later version.
Please update _Lewaind's Third Person_ to the latest version and try again.
