### ISSUE TITLE
I think the game crash because of Third Person

### ISSUE THREAD

**Issue by CaoTrongThang** [Leawind/Third-Person#169]
## Describe the bug

I keep randomly crashing i think, and i see your mod name in the Mixins Stacktrace, I don't really know, it has been crashing for months now

## Reproduce

I just loaded the game's worlds with many mods

## Expected behavior

I expected it doesn't crash

## Additional context
Log: https://mclo.gs/fNtJnfg
Crash log: [crash-2024-11-01_20.30.59-client.txt](https://github.com/user-attachments/files/17600149/crash-2024-11-01_20.30.59-client.txt)

**Comment by Leawind** [comment]
Thank you for reporting this, but it seems to be an issue with the architectury api rather than this mod. Does this problem occur every time you enter the world, or is it random?

**Comment by CaoTrongThang** [comment]
> Thank you for reporting this, but it seems to be an issue with the architectury api rather than this mod. Does this problem occur every time you enter the world, or is it random?

It's very random and I've asked some people in the Community, they said it maybe because of the Sounds mod, can you take a look at the log?, I sent them the same log that I sent you above.

**Comment by Leawind** [comment]
> they said it maybe because of the Sounds mod

I find that mod _Sounds_ includes some dependencies in its released jar file, including:

* Architectury-api
* mixinextras
* yet-another-config-lib

Usually when a mod depends other mods, it only claim the dependencies but not include them.

I don't know if there is a special reason why _Sounds_ do this. But you can try removing architectury-api file from _sounds_ and see if it work.

Its path is `META-INF/jars/architectury-fabric-9.2.14.jar`. It's inside the file `Sounds-2.1.0+1.20.1+fabric.jar`

**Comment by CaoTrongThang** [comment]
Ok thank you, i'll try
