### ISSUE TITLE
Flowers or tall grass generate a change in camera direction

### ISSUE THREAD

**Issue by Matiarguello** [Leawind/Third-Person#171]
## Describe the bug

It seems that the hitbox of tall grass and some flowers (like sunflowers) causes the player to change direction, which is very annoying in some biomes with a lot of grass and flowers like this one:

![aa](https://github.com/user-attachments/assets/0a6a45e9-e98b-4077-bb6a-fb93df7dc12b)

## Reproduce

[![](https://markdown-videos-api.jorgenkh.no/youtube/pQ0PdunL3Mo)](https://youtu.be/pQ0PdunL3Mo)

## Expected behavior

This happens with any flower, whether vanilla or modded. It would be ideal if this hitbox could somehow be ignored or not changed direction.

**Comment by Inter-link** [comment]
@Leawind hello, is there an update to this? This is really one thing that would make third person more usable
