### ISSUE TITLE
Leawind's Third Person x Crosshair Bobbing Compat

### ISSUE THREAD

**Issue by spunchbop121** [Leawind/Third-Person#30]

**Comment by Leawind** [comment]
Similar to https://github.com/Exopandora/ShoulderSurfing/issues/161

**Comment by Leawind** [comment]
The mod disables itself when not in 3rd person, see https://github.com/Krash220/CrosshairBobbingMod/blob/main/game/fabric1.16.2/src/main/java/krash220/xbob/game/api/Render.java#L28
