### ISSUE TITLE
When going to high speeds the player goes away too much.

### ISSUE THREAD

**Issue by Leawind** [Leawind/Third-Person#31]
is there an option to set how much the player will offset when moving?
when going to high speeds the player goes away too much.
![image](https://github.com/LEAWIND/Third-Person/assets/90531548/ebea2c40-84bb-4b8c-9b6c-290da9e4a0f2)

_Originally posted by @Trickster-4 in https://github.com/LEAWIND/Third-Person/issues/12#issuecomment-1885612975_

**Comment by Trickster-4** [comment]
hey thanks for making this thread! i recommend making a slider to tweak the distance, like a multiplier.
so it changes the value the camera uses to move to the player's back.
because for example, you could also add a negative value to it that makes the camera move foward instead.

**Comment by Leawind** [comment]
fixed in 442d65c
