### ISSUE TITLE
Z not adjusting camera

### ISSUE THREAD

**Issue by 0KSTONE** [Leawind/Third-Person#33]
Im having trouble adjusting the camera. Holding the z button does not allow me to adjust the camera it just centers the camera. The camera is too far over for me and i cant adjust. It was said that caps lock centers the camera but that doesn't do anything at all.

**Comment by Leawind** [comment]
which version are you using?

**Comment by 0KSTONE** [comment]
Im using version 1.20.1

i do have quite a few other mods installed so maybe its clashing with something but I don't have any that affect perspective.

**Comment by Leawind** [comment]
It may be due to key conflict. Are there other keys set to Z?

**Comment by 0KSTONE** [comment]
There was at first with Xaero's minimap but when i changed it that didnt help.

**Comment by Leawind** [comment]
I'll port the new version to 1.20 few days later. If the problem still exist I'll dig into it.

**Comment by s-j-y-m** [comment]
Perhaps you could try switching perspectives a few more times or looking at the configuration file?

**Comment by 0KSTONE** [comment]
> Perhaps you could try switching perspectives a few more times or looking at the configuration file?

tried switching perspectives but i didnt take a look at the config folder so that may help.
