### ISSUE TITLE
Compat for do a barrel roll

### ISSUE THREAD

**Issue by juice-ix** [Leawind/Third-Person#36]
Not so much an issue, more like a request. It only works halfway when in third person, you can't turn using a/d (im pretty sure, i haven't gone and done a lot of testing) and you can't go up or down with the camera.

**Comment by s-j-y-m** [comment]
啊兄弟咱两想一块去了
滚筒配这个确实好玩
但是这个问题应该是由于该MOD的第三人称只是摄像机移动而非角色移动导致的

**Comment by Leawind** [comment]
1.19.2 fabric works fine
1.19.2 forge crashed due to mixin conflict

I find do_a_barrel_roll fabric is using `com.llamalad7.mixinextras.injector.WrapWithCondition` on `net.minecraft.client.Mouse#updateMouse`
while the forge version is using `org.spongepowered.asm.mixin.injection.Redirect`
