### ISSUE TITLE
1.20.1 version crashing

### ISSUE THREAD

**Issue by MagyTheMage** [Leawind/Third-Person#41]
I do have a rather large modpack which i wanted to add this mod on, but it seems like for some reason upon adding this mod. The entire game will "freeze"

With freeze, i dont mean the program crashing, i just mean that entities will no longer move and the player will no longer be able to interact with the world, chunks will cease to load etc.

I am unsure if its an incompability with my other mods or this mod in particular but i can guarantee that this mod is the one springing the issue because removing it seems to correct it

[debug.log](https://github.com/LEAWIND/Third-Person/files/14230201/debug.log)
[latest.log](https://github.com/LEAWIND/Third-Person/files/14230200/latest.log)

**Comment by Leawind** [comment]
Does it still freeze in v2.0.8-beta.2 ?

**Comment by MagyTheMage** [comment]
tested using v2.0.8-beta.2 and v.2.0.8-beta.3  and both will crash the game on boot.

[crash-2024-03-10_13.51.43-fml.txt](https://github.com/LEAWIND/Third-Person/files/14551077/crash-2024-03-10_13.51.43-fml.txt)

report seems to blame xaeros world map so i attempted to remove both of xaeros mods yet the crash was not solved. no new crash reports were added despite this

[latest.log](https://github.com/LEAWIND/Third-Person/files/14551095/latest.log)
[debug.log](https://github.com/LEAWIND/Third-Person/files/14551096/debug.log)

**Comment by Leawind** [comment]
I find this in your `latest.log`:
```
Mod ID: 'architectury', Requested by: 'leawind_third_person', Expected range: '[9.2.14,)', Actual version: '9.1.12'
```
Update the architectury to 9.2.14 and try again

**Comment by MagyTheMage** [comment]
Works fine now!
