### ISSUE TITLE
Crash on generated world load

### ISSUE THREAD

**Issue by Lombaxtard** [Leawind/Third-Person#42]
Crashes on world load until this mod is disabled, I can then re-enable it in-game and it works as if nothing hapenned
[crash-2024-02-19_06.14.45-client.txt](https://github.com/LEAWIND/Third-Person/files/14326070/crash-2024-02-19_06.14.45-client.txt)

**Comment by Leawind** [comment]
I haven't found out the specific reason yet.
But this problem doesn't seem to exist in the latest version because I did some refactoring in later versions.

**Comment by Lombaxtard** [comment]
> I haven't found out the specific reason yet. But this problem doesn't seem to exist in the latest version because I did some refactoring in later versions.

It's honestly a pain to reproduce as this crash appears to be somewhat random - I can play for a while, log off at a certain spot, then when I come back I get a crash until I disable the mod temporarily. Then I keep on playing, and I can log on and off multiple times without any issues even when in previously "problematic" chunks, as well as throughout the world
But that's my story as of 1.19.2, crashing was a lot more frequent in 1.18.2. Anyway, thanks for your attempted support. I'm enjoying your criminally underrated mod immensely
P.S. Hoping you're gonna get some more recognition soon, as your mod was very recently featured on <a href="https://www.youtube.com/@AsianHalfSquat">AsianHalfSquat</a> on YT
