### ISSUE TITLE
Crashed when trying to join a world.

### ISSUE THREAD

**Issue by CaptConrad** [Leawind/Third-Person#44]
After installing the latest version, I can't join a world. It just crashes when I try to join. 
[crash-2024-02-25_14.22.38-client.txt](https://github.com/LEAWIND/Third-Person/files/14397534/crash-2024-02-25_14.22.38-client.txt)

**Comment by Leawind** [comment]
I see you are using version 2.0.4
Does the problem presist in 2.0.5 ?

**Comment by EuBruno1** [comment]
I can Confirm that the problem persists in 2.0.5.
Thank you very much!

**Comment by Leawind** [comment]
fixed in 03ad03a
