### ISSUE TITLE
flagged as virus by windows defender

### ISSUE THREAD

**Issue by ThatKatNaps** [Leawind/Third-Person#48]
all downloads of version 2.0.8-beta.1 both fabric and forge, are marked as trojan script/wacatac.b ml

This is on the pre-release on github, the beta dl on modrinth, and the beta dl on curseforge

**Comment by kessler06** [comment]
this also happen to me too

**Comment by Leawind** [comment]
This is weird.
If there is indeed a virus in the mod, it might originate from the dependency packages.
The released versions 2.0.8-beta.1 and 2.0.8-beta.2 include a jar file: [MixinsExtras](https://github.com/LlamaLad7/MixinExtras). It is also open source and unlikely to contain any viruses.
Considering that Windows Defender often falsely flags legitimate files, I believe the mod files are safe.
My personal solution is to disable Windows Defender (not recommended), I don't know if there is a better way.
