### ISSUE TITLE
2.0.8 beta 2 Fabric 1.20.1 incompatibility with "First Person Model" mod

### ISSUE THREAD

**Issue by 3ncanis** [Leawind/Third-Person#51]
Cannot see first person body (or even arms) when using the First-person Model mod. https://modrinth.com/mod/first-person-model, from what I understand this mod uses your third person model while you're in first person view. Thanks for fixing the mouse sensitivity issue btw

**Comment by Leawind** [comment]
Same reason with #50 
Solved in 490b9ca
