### ISSUE TITLE
 The mod crashes minecraft if used with cloth config

### ISSUE THREAD

**Issue by ElTrollGuy** [Leawind/Third-Person#55]
I tried using cloth config to change some stuff in the mod but when I install cloth config the game doesn't even launch it just crashes. The version I'm using is 1.19.2

**Comment by Leawind** [comment]
Could you provide the crash report?

**Comment by ElTrollGuy** [comment]
[crash-2024-03-10_13.36.48-client.txt](https://github.com/LEAWIND/Third-Person/files/14549705/crash-2024-03-10_13.36.48-client.txt)
here

**Comment by Leawind** [comment]
Looks like the same as https://github.com/Asek3/Oculus/issues/395

> I got the result !
> This was a dependency error. In fact, I haven't installed a mod called Mekanism for his add-ons.
> 
> How to reproduce
> 
> Open the Latest log.txt
> Normally you will see an error saying [main/ERROR]: Missing or unsupported mandatory dependencies:
> The following mods are missing, just download the mod and you will be clear!
> Example Latest log
> See Line 184
> https://mclo.gs/gOicwQe
