### ISSUE TITLE
The Game crashes after opening

### ISSUE THREAD

**Issue by Stiefanek** [Leawind/Third-Person#59]
[latest.log](https://github.com/LEAWIND/Third-Person/files/14551170/latest.log)
this is my log i am using 1.20.1

**Comment by Stiefanek** [comment]
(also please port it to 1.20.4)

**Comment by Leawind** [comment]
《fabric-api 0.96.4+1.20.4》

Try switch to version for 1.20.1 and try again. If then it works, you can close this issue.
