### ISSUE TITLE
Incompatible with 'Jade'

### ISSUE THREAD

**Issue by MarioBlare** [Leawind/Third-Person#63]
## Describe
Jade does not display information in third-person mode.

## Reproduce
1. Put Leawind's Third Person and [Jade](https://modrinth.com/mod/jade) in the same modpack
2. Go into the world and look at the various blocks in third-person mode
3. Jade will almost never display a banner with information

## Expected behavior
Jade should always display information about the blocks you are looking at.

## Additional context
Tested with newest versions of Forge (47.2.20), Architectury API (9.2.14), Cloth Config API (11.1.118), Jade (11.8.0), Leawind's Third Person (2.0.8 Beta 3) and nothing more. Incompatibility does not cause warnings or errors in the log files.

I think the Jade is getting incorrect information about where the crosshair is pointing. Pressing the RMB redirects the view and Jade is triggered for a short time.

**Comment by Leawind** [comment]
## Observed behavior

![2024-03-13_22 01 07](https://github.com/LEAWIND/Third-Person/assets/49919003/af7a7f84-d7ae-4d42-94fb-571a69da60f0)

## Expected behavior

![2024-03-13_21 59 12](https://github.com/LEAWIND/Third-Person/assets/49919003/9184fce8-27e6-4f58-a1ea-c982c024c204)

**Comment by bubin7766** [comment]
### Noticed Issue
I've noticed that even when pressing RMB to force the character to look at the entity
The crosshair being used does not utilize the "True Crosshair" much like in #56

In this case I used the mod called [Interactic](https://modrinth.com/mod/interactic) which shows tooltips on dropped items
To test this I disabled "Right Click Pickup" as well as "Auto Pickup"
After that the behavior is exactly the same as with Jade
