### ISSUE TITLE
生存模式无法和方块交互

### ISSUE THREAD

**Issue by nanachijiang** [Leawind/Third-Person#64]
游戏版本：1.20.1
mod版本：beta3
只安装了Leawind_third_person模组和其前置 Architectury

https://github.com/LEAWIND/Third-Person/assets/149419724/0157c66f-7224-44a8-807e-a9ca1185ac64

如视频所示，创造模式下交互正常，生存模式无法挖掘方块以及和箱子、门等方块进行交互。
并非完全无法交互，而是交互范围非常小，只有低头看地面的时候在某个特定角度可以交互。

**Comment by Leawind** [comment]
fixed in 0a82f7e2cac37036e5af786ec3c8c77d06f2277d
