### ISSUE TITLE
Non compatible with armor trims

### ISSUE THREAD

**Issue by ItsNathanity** [Leawind/Third-Person#65]
When using third person with the mod, armor trims are not visible.
 Apon deleting the mod, the trims are visible. 

I'm experiencing this on 1.20.1 although I haven't testing if it's patched on other versions.

**Comment by Leawind** [comment]
I can't reproduce it on 2.0.8-beta.4-mc1.20.1
Maybe due to conflict with other mod?
However I did some modification b5cb63f7f541543006051980d397496506f354a4, which may solve this.

**Comment by Leawind** [comment]
I reproduced this when iris installed. I'll see how to fix this...

And armor trims will be visible if you disable player fade out.

**Comment by Leawind** [comment]
By now the solution is to disable player fade out in config.
Because this feature seems to conflict with Iris.

Player fade out is now disabled by default.
