### ISSUE TITLE
Incompatible with epicfight

### ISSUE THREAD

**Issue by iekiekkeikei** [Leawind/Third-Person#72]
## Describe

The camera is forced to be centred on the player when attacking.

## Reproduce

1. put the player in combat mode.
2. put the player in third person view.
3. attack.
4. force the camera to centre on the player.

## Expected behavior

When attacking during combat mode, the third-person camera is momentarily centred on the player.

## Additional context

No log.

**Comment by Tapacywka** [comment]
The Epic Fight bug happens in both the Shoulder Surfing Reloaded, Better Third Person, and Camera Utils mods.
There should most likely be a fix from the Epic Fight developer or a joint integration with them.

**Comment by iekiekkeikei** [comment]
Okay.
I'll put it out on the issue over there.

**Comment by iekiekkeikei** [comment]
Addendum: Ver 1.0.1 does not have this problem.

**Comment by Raiiiden** [comment]
> The Epic Fight bug happens in both the Shoulder Surfing Reloaded, Better Third Person, and Camera Utils mods. There should most likely be a fix from the Epic Fight developer or a joint integration with them.

The problem is they need Leawind to help them to make the fix. Epic Fight is working on the fixes for all of these and is waiting on Leawind now I believe

**Comment by Leawind** [comment]
It's fixed In the newest release 2.0.9-beta.1
