### ISSUE TITLE
Camera rotates 180 degrees when walking through some blocks

### ISSUE THREAD

**Issue by voidedcy** [Leawind/Third-Person#76]
## Describe the bug

If your camera walks over a non-solid block (such as grass, flowers, vines, etc...) your camera rotates 180 degrees

## Reproduce

Just walk over a non-solid block with thirdperson active

video: https://youtu.be/LOgidPsiNZ4

## Expected behavior

The camera shouldnt change when walking over non-solid blocks

**Comment by bubin7766** [comment]
This looks like you added the mod to a mod pack, have you tried disabling other mods that alter third person to see what it is conflicting with?

**Comment by voidedcy** [comment]
created a video with your mod only:

https://youtu.be/P5Rw7fFaNRk

**Comment by bubin7766** [comment]
What version are you playing on, what loader is it for, and what version is the mod?

**Comment by voidedcy** [comment]
1.19.2, forge 43.3.8 release, and the mod is v2.0.7

im using curseforge

**Comment by bubin7766** [comment]
Leawind has fixed this in the newest preview update, once it is stable it will get updated for 1.19.2
