### ISSUE TITLE
[Bug] [Fabric 1.20.1] While in first person, using a spyglass resets your camera angle

### ISSUE THREAD

**Issue by AncletYinglet** [Leawind/Third-Person#78]
## Describe the bug

When using a spyglass in first person, after exiting third person, your camera view will snap to whatever direction you were looking in third person.

## Reproduce

1. Go into third person view, then return to first person
2. Use spyglass in first person view
3. Camera view will snap to the direction you were last looking in, in third person

## Expected behavior

Camera should not snap to any direction and still be looking where you were in first person before zooming in with the spyglass.

## Additional context

Tested on a fresh world with no other mods aside from this one. Game version is 1.20.1, mod version is v2.0.8-beta.5.

**Comment by PierreHervelin** [comment]
Same with using "temporarily enter first person when used" config option for bow and crossbow.
When I use my bow in third person, there is no bug, but when I use my bow in first person the bug appears

**Comment by GrandmaPork** [comment]
can confirm for forge 1.20.1 as well

**Comment by Leawind** [comment]
fixed in 7703fb0292e3c427a904773b60d6b4b0f94b272b
