### ISSUE TITLE
Incompatible with 'Valkyrie Skies for 1.20.1'

### ISSUE THREAD

**Issue by 704009905** [Leawind/Third-Person#79]
## Describe

With both Valkyrie Skies and Leawind's Third Person enabled, the player cannot place(use) blocks.

## Reproduce 
1. Install Valkyrie Skies and Leawind's Third Person on Forge 1.20.1
2. Join a world and place a block in the third person

## Expected behaviour

The player should place the block as normal.

## Additional context

On placing the block, no logs are output. No unusual logs on Valkyrie Skies. No other bugs were noticed with Valkyrie Skies.

Placing blocks in first person, vanilla third person and duration smooth transition from first person to third person works normally. On the first seconds of world join, sometimes it may be able to place one block, on the wrong camera place.

A rough guess: Valkyrie Skies implemented a special ray cast for checking to place blocks on physics entities, maybe it conflicts with Leawind's Third Person.

**Comment by Myakishow** [comment]
I confirm

**Comment by Gorehuchi** [comment]
Also experiencing this issue

**Comment by Spac3B3nd3r** [comment]
I too have this issue. I am using a custom fork for Valkyrian skies on 1.20.1

**Comment by myPI314by** [comment]
This is the issue I experienced. It's odd that it applies even when not interacting with Valkyrien Skies builds.

**Comment by raffle2** [comment]
Also have the same issue on forge 1.20.1
