### ISSUE TITLE
Crash when glowing and entering third person

### ISSUE THREAD

**Issue by AzrannAVANA** [Leawind/Third-Person#80]
## When player has the glowing effect

Select one:

* Enter third person

## Crash report

Please upload the crash report file.
[crash-2024-04-06_00.26.56-server.txt](https://github.com/LEAWIND/Third-Person/files/14891569/crash-2024-04-06_00.26.56-server.txt)
[crash-2024-04-06_01.13.30-client.txt](https://github.com/LEAWIND/Third-Person/files/14891570/crash-2024-04-06_01.13.30-client.txt)

## Additional mods installed
Embeddium & Others
First Person Model

**Comment by emorydeer2** [comment]
Can confirm. It is specifically any perspective change, period.
