### ISSUE TITLE
Update to 1.20.4 please

### ISSUE THREAD

**Issue by aurorarissime** [Leawind/Third-Person#86]
Hi! I found this mod to be the best for my rpg oriented modpack, but unfortunately I'm making it in 1.20.4, and this mod isn't available. I still tried to use it but the game crashes whenever scroll up or down (because it changes the distance of the camera). Could you officially update it to the latest Fabric version please? Thanks a lot :)

**Comment by ArctynFox** [comment]
I've made a fix for this issue (https://github.com/LEAWIND/Third-Person/pull/88), but it seems like the developer has been pretty inactive with this project lately. You can find the jar files [here](https://github.com/ArctynFox/Third-Person/releases/tag/v2.0.8-beta.5-mc1.20.4).

**Comment by aurorarissime** [comment]
I can see that, and thank you a lot for your work, but for a public modpack I would prefer / need an official release 😬

**Comment by CrocSavage** [comment]
> I've made a fix for this issue (#88), but it seems like the developer has been pretty inactive with this project lately. You can find the jar files [here](https://github.com/ArctynFox/Third-Person/releases/tag/v2.0.8-beta.5-mc1.20.4).

Hey bro it's a longshot but could you port this up to 1.20.6 as well?
