### ISSUE TITLE
[BUG]the mod did not work properly when the character was in the high grass. 

### ISSUE THREAD

**Issue by NpTIme** [Leawind/Third-Person#94]
我英语太垃圾了还是用中文讲吧

在新版本[2.0.7]的1.19.4版本中,当玩家操控的人物进入到高草丛中时, 摄像机会移动至卡进人物头部中.

或者换个形式说,摄像机的运动会被藤蔓,草丛等阻挡,而不是穿过它们

这种情况会导致人物在草原,树林等地形移动时摄像头会不停乱跳,导致画面的割裂感严重,

附一张卡草丛的图

![2024-05-14_14 55 09](https://github.com/LEAWIND/Third-Person/assets/140777598/fa1395ce-4dc4-4844-bfd9-47e1c24a9908)

**Comment by NpTIme** [comment]
再附一张正常工作的图(2.0.2)🥰

![2024-05-17_23 25 41](https://github.com/LEAWIND/Third-Person/assets/140777598/eaa0dbe4-35f5-415a-8f50-91eec9c6eeee)

**Comment by s-j-y-m** [comment]
作者是国人哦
在B站还有账号

**Comment by LEAWIND** [comment]
可能是半透明功能的bug，试一下在配置里关掉玩家虚化

**Comment by NpTIme** [comment]
> 作者是国人哦 在B站还有账号

i know

**Comment by NpTIme** [comment]
FIxed?

**Comment by Leawind** [comment]
其实在1.20.1的新版本里已经解决了，但是还没有移植到1.19来
