### ISSUE TITLE
Crash when Join a world

### ISSUE THREAD

**Issue by Merrick-Charles** [Leawind/Third-Person#95]
当进入地图时崩溃，pcl显示崩溃原因未知，mod包为生电fabric包，fabric和建筑api均为最新版本，关闭其他所有美化mod还是不行，请教各位大神
[crash-2024-05-18_10.40.51-client.txt](https://github.com/LEAWIND/Third-Person/files/15359616/crash-204-05-18_10.40.51-client.txt)

**Comment by Leawind** [comment]
看不到日志耶，重新上传一下咯

![image](https://github.com/LEAWIND/Third-Person/assets/49919003/53ae6ee2-ee52-415d-82bb-8ef65d2876e8)

**Comment by Merrick-Charles** [comment]
[Uploading crash-2024-05-18_10.40.51-client.txt…]()

**Comment by Merrick-Charles** [comment]
[crash-2024-05-18_10.40.51-client.txt](https://github.com/LEAWIND/Third-Person/files/15359759/crash-2024-05-18_10.40.51-client.txt)

**Comment by Leawind** [comment]
可能是半透明功能的bug，试一下在配置里关掉玩家虚化
