### ISSUE TITLE
与机械动力:火炮不兼容（1.20）

### ISSUE THREAD

**Issue by LiYuqin4096** [Leawind/Third-Person#98]
在使用模组中的带把手的机炮时，视角会异常转动

https://github.com/Leawind/Third-Person/assets/170216871/68f184eb-6e65-44dd-88cd-7939d2a05389

**Comment by LiYuqin4096** [comment]
1.19也有这种问题

**Comment by LiYuqin4096** [comment]
似乎是机炮的视线不会转动导致的

**Comment by Leawind** [comment]
1.20.1的最新版可能已经修复了，你能测试一下吗

**Comment by LiYuqin4096** [comment]
确实修复了

**Comment by Leawind** [comment]
好耶

**Comment by LiYuqin4096** [comment]
好耶
